import type { IPagedResults } from "../types/pagnigate";
import type { Product } from "../types/product.type";

export const productsDummyData: IPagedResults<Product> = {
  data: [
    {
      id: 1,
      code: "Á-1",
      urlHandle: "ao-khoac-gio-the-thao-nam-1-lop-chong-tia-uv-1",
      name: "Áo Khoác Gió Thể Thao Nam 1 Lớp Chống Tia UV",
      metaDesc:
        "Mẫu áo khoác chất liệu nhẹ, mỏng, tạo cảm giác thoải mái khi mặc. Chống thấm nước tốt, giúp bạn luôn khô ráo trong những cơn mưa bất chợt. Chống tia UV UPF50+, bảo vệ da khỏi tác hại của ánh nắng mặt trời. Khô nhanh, hạn chế vi khuẩn phát triển.",
      display: true,
      inventoryStatus: true,
      originalPrice: "599000",
      salePrice: "98770",
      createdDate: "2025-05-25T09:49:22.838Z",
      updatedDate: "2025-05-25T09:49:24.432Z",
      promotionId: null,
      categoryId: 4,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 4,
        name: "Áo khoác nam",
        urlHandle: "Ao-khoac-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 1,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/1/0",
          position: 0,
          productId: 1,
          colorId: 1,
        },
        {
          id: 2,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/1/1",
          position: 1,
          productId: 1,
          colorId: 1,
        },
        {
          id: 3,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/1/2",
          position: 2,
          productId: 1,
          colorId: 1,
        },
        {
          id: 4,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/2/0",
          position: 0,
          productId: 1,
          colorId: 2,
        },
        {
          id: 5,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/2/1",
          position: 1,
          productId: 1,
          colorId: 2,
        },
        {
          id: 6,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-1/2/2",
          position: 2,
          productId: 1,
          colorId: 2,
        },
      ],
      variants: [
        {
          id: 8,
          code: "Á-1-XÁM-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 4,
          productId: 1,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 7,
          code: "Á-1-XÁM-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 3,
          productId: 1,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 6,
          code: "Á-1-XÁM-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 2,
          productId: 1,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 5,
          code: "Á-1-XÁM-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 1,
          productId: 1,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
        {
          id: 4,
          code: "Á-1-ĐEN-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 4,
          productId: 1,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 3,
          code: "Á-1-ĐEN-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 3,
          productId: 1,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 2,
          code: "Á-1-ĐEN-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 2,
          productId: 1,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 1,
          code: "Á-1-ĐEN-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 1,
          productId: 1,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
      ],
      colors: [
        {
          id: 1,
          name: "ĐEN",
        },
        {
          id: 2,
          name: "XÁM",
        },
      ],
    },
    {
      id: 2,
      code: "Á-2",
      urlHandle: "ao-khoac-nam-bomber-phoi-lot-2",
      name: "Áo Khoác Nam Bomber Phối Lót",
      metaDesc:
        "Mẫu áo khoác chất liệu nhẹ, mỏng, tạo cảm giác thoải mái khi mặc. Chống thấm nước tốt, giúp bạn luôn khô ráo trong những cơn mưa bất chợt. Chống tia UV UPF50+, bảo vệ da khỏi tác hại của ánh nắng mặt trời. Khô nhanh, hạn chế vi khuẩn phát triển.",
      display: true,
      inventoryStatus: true,
      originalPrice: "899000",
      salePrice: null,
      createdDate: "2025-05-25T09:57:53.339Z",
      updatedDate: "2025-05-25T09:57:54.868Z",
      promotionId: null,
      categoryId: 4,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 4,
        name: "Áo khoác nam",
        urlHandle: "Ao-khoac-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 7,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/2/0",
          position: 0,
          productId: 2,
          colorId: 2,
        },
        {
          id: 8,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/2/1",
          position: 1,
          productId: 2,
          colorId: 2,
        },
        {
          id: 9,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/2/2",
          position: 2,
          productId: 2,
          colorId: 2,
        },
        {
          id: 10,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/8/0",
          position: 0,
          productId: 2,
          colorId: 8,
        },
        {
          id: 11,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/8/1",
          position: 1,
          productId: 2,
          colorId: 8,
        },
        {
          id: 12,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-2/8/2",
          position: 2,
          productId: 2,
          colorId: 8,
        },
      ],
      variants: [
        {
          id: 16,
          code: "Á-2-BE-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 4,
          productId: 2,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 15,
          code: "Á-2-BE-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 3,
          productId: 2,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 14,
          code: "Á-2-BE-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 2,
          productId: 2,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 13,
          code: "Á-2-BE-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 1,
          productId: 2,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
        {
          id: 12,
          code: "Á-2-XÁM-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 4,
          productId: 2,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 11,
          code: "Á-2-XÁM-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 3,
          productId: 2,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 10,
          code: "Á-2-XÁM-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 2,
          productId: 2,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 9,
          code: "Á-2-XÁM-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 1,
          productId: 2,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
      ],
      colors: [
        {
          id: 2,
          name: "XÁM",
        },
        {
          id: 8,
          name: "BE",
        },
      ],
    },
    {
      id: 3,
      code: "Á-3",
      urlHandle: "ao-khoac-ni-the-thao-nam-performance-3",
      name: "Áo Khoác Nỉ Thể Thao Nam Performance",
      metaDesc:
        "Kiểu dáng Slim fit ôm sát tôn lên đường nét cơ thể, giúp bạn tự tin và khoẻ khoắn trong mọi hoạt động từ đi làm, đi chơi đến dự tiệc. Sản phẩm hoàn hảo cho phái mạnh hiện đại - tự tin khẳng định phong cách.",
      display: true,
      inventoryStatus: true,
      originalPrice: "579000",
      salePrice: null,
      createdDate: "2025-05-25T09:59:35.292Z",
      updatedDate: "2025-05-25T09:59:36.679Z",
      promotionId: null,
      categoryId: 4,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 4,
        name: "Áo khoác nam",
        urlHandle: "Ao-khoac-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 13,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/2/0",
          position: 0,
          productId: 3,
          colorId: 2,
        },
        {
          id: 14,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/2/1",
          position: 1,
          productId: 3,
          colorId: 2,
        },
        {
          id: 15,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/2/2",
          position: 2,
          productId: 3,
          colorId: 2,
        },
        {
          id: 16,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/7/0",
          position: 0,
          productId: 3,
          colorId: 7,
        },
        {
          id: 17,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/7/1",
          position: 1,
          productId: 3,
          colorId: 7,
        },
        {
          id: 18,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-3/7/2",
          position: 2,
          productId: 3,
          colorId: 7,
        },
      ],
      variants: [
        {
          id: 24,
          code: "Á-3-NÂU-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 4,
          productId: 3,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 23,
          code: "Á-3-NÂU-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 3,
          productId: 3,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 22,
          code: "Á-3-NÂU-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 2,
          productId: 3,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 21,
          code: "Á-3-NÂU-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 1,
          productId: 3,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
        {
          id: 20,
          code: "Á-3-XÁM-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 4,
          productId: 3,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 19,
          code: "Á-3-XÁM-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 3,
          productId: 3,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 18,
          code: "Á-3-XÁM-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 2,
          productId: 3,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 17,
          code: "Á-3-XÁM-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 1,
          productId: 3,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
      ],
      colors: [
        {
          id: 2,
          name: "XÁM",
        },
        {
          id: 7,
          name: "NÂU",
        },
      ],
    },
    {
      id: 4,
      code: "Á-4",
      urlHandle: "ao-khoac-nam-bomber-bo-nguc-4",
      name: "Áo Khoác Nam Bomber Bổ Ngực",
      metaDesc:
        "Áo khoác bomber nam cá tính với thiết kế bổ ngực trẻ trung, năng động. Sản phẩm co giãn 4 chiều thoải mái, cản gió giữ ấm hiệu quả nhờ chất liệu nylon cao cấp và kiểu dệt đặc biệt. Sợi spandex cho phép áo co giãn tối đa, thoải mái mọi hoạt động.",
      display: true,
      inventoryStatus: true,
      originalPrice: "350000",
      salePrice: null,
      createdDate: "2025-05-25T10:00:50.520Z",
      updatedDate: "2025-05-25T10:00:51.850Z",
      promotionId: null,
      categoryId: 4,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 4,
        name: "Áo khoác nam",
        urlHandle: "Ao-khoac-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 19,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/1/0",
          position: 0,
          productId: 4,
          colorId: 1,
        },
        {
          id: 20,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/1/1",
          position: 1,
          productId: 4,
          colorId: 1,
        },
        {
          id: 21,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/1/2",
          position: 2,
          productId: 4,
          colorId: 1,
        },
        {
          id: 22,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/3/0",
          position: 0,
          productId: 4,
          colorId: 3,
        },
        {
          id: 23,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/3/1",
          position: 1,
          productId: 4,
          colorId: 3,
        },
        {
          id: 24,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-4/3/2",
          position: 2,
          productId: 4,
          colorId: 3,
        },
      ],
      variants: [
        {
          id: 32,
          code: "Á-4-XANH DƯƠNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 4,
          productId: 4,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 31,
          code: "Á-4-XANH DƯƠNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 3,
          productId: 4,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 30,
          code: "Á-4-XANH DƯƠNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 2,
          productId: 4,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 29,
          code: "Á-4-XANH DƯƠNG-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 1,
          productId: 4,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
        {
          id: 28,
          code: "Á-4-ĐEN-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 4,
          productId: 4,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 27,
          code: "Á-4-ĐEN-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 3,
          productId: 4,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 26,
          code: "Á-4-ĐEN-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 2,
          productId: 4,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 25,
          code: "Á-4-ĐEN-S",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 1,
          productId: 4,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 1,
            name: "S",
          },
        },
      ],
      colors: [
        {
          id: 1,
          name: "ĐEN",
        },
        {
          id: 3,
          name: "XANH NAVY",
        },
      ],
    },
    {
      id: 5,
      code: "Á-5",
      urlHandle: "ao-so-mi-nam-dai-tay-tui-kieu-5",
      name: "Áo Sơ Mi Nam Dài Tay Túi Kiểu",
      metaDesc:
        "Chất liệu: vải sơ mi cotton lóng chéo twill\n\nThành phần:70% Cotton, 30% Tencel\n\nƯu điểm chất liệu:\n\nThoáng mát & tự nhiên: Sợi Cotton truyền thống giúp vải thông thoáng, dễ chịu khi mặc.\n\nMềm mại vượt trội: Kết hợp sợi Tencel tăng độ êm ái, mang lại cảm giác nhẹ nhàng trên da.\n\nBề mặt bền chắc: Kiểu dệt bền chắc đảm bảo độ căng chắc vừa vặn, tôn lên vẻ ngoài sang trọng.\n\nĐặc điểm thiết kế:\n\nThiết kế tiện lợi: Kiểu dáng cơ bản với túi ngực, vừa đơn giản vừa tinh tế.\n\nThoải mái & linh hoạt: Phom suông rộng rãi, ly sau lưng giúp cử động dễ dàng.\n\nĐiểm nhấn trẻ trung: Cúc phối nổi tạo nét hiện đại, cá tính.",
      display: true,
      inventoryStatus: true,
      originalPrice: "590000",
      salePrice: null,
      createdDate: "2025-05-25T10:03:33.065Z",
      updatedDate: "2025-05-25T10:03:34.606Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 25,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/6/0",
          position: 0,
          productId: 5,
          colorId: 6,
        },
        {
          id: 26,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/6/1",
          position: 1,
          productId: 5,
          colorId: 6,
        },
        {
          id: 27,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/6/2",
          position: 2,
          productId: 5,
          colorId: 6,
        },
        {
          id: 28,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/3/0",
          position: 0,
          productId: 5,
          colorId: 3,
        },
        {
          id: 29,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/3/1",
          position: 1,
          productId: 5,
          colorId: 3,
        },
        {
          id: 30,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-5/3/2",
          position: 2,
          productId: 5,
          colorId: 3,
        },
      ],
      variants: [
        {
          id: 40,
          code: "Á-5-TRẮNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 5,
          productId: 5,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 39,
          code: "Á-5-TRẮNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 4,
          productId: 5,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 38,
          code: "Á-5-TRẮNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 3,
          productId: 5,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 37,
          code: "Á-5-TRẮNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 2,
          productId: 5,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 36,
          code: "Á-5-XANH DƯƠNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 5,
          productId: 5,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 35,
          code: "Á-5-XANH DƯƠNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 4,
          productId: 5,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 34,
          code: "Á-5-XANH DƯƠNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 3,
          productId: 5,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 33,
          code: "Á-5-XANH DƯƠNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 2,
          productId: 5,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 3,
          name: "XANH NAVY",
        },
        {
          id: 6,
          name: "TRẮNG",
        },
      ],
    },
    {
      id: 6,
      code: "Á-6",
      urlHandle: "ao-polo-nam-bo-det-in-ke-6",
      name: "Áo Polo Nam Bo Dệt In Kẻ",
      metaDesc:
        "Kiểu dáng Slim fit ôm sát tôn lên đường nét cơ thể, giúp bạn tự tin và khoẻ khoắn trong mọi hoạt động từ đi làm, đi chơi đến dự tiệc. Sản phẩm hoàn hảo cho phái mạnh hiện đại - tự tin khẳng định phong cách.",
      display: true,
      inventoryStatus: true,
      originalPrice: "350000",
      salePrice: null,
      createdDate: "2025-05-25T10:04:54.976Z",
      updatedDate: "2025-05-25T10:04:56.325Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 31,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/1/0",
          position: 0,
          productId: 6,
          colorId: 1,
        },
        {
          id: 32,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/1/1",
          position: 1,
          productId: 6,
          colorId: 1,
        },
        {
          id: 33,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/1/2",
          position: 2,
          productId: 6,
          colorId: 1,
        },
        {
          id: 34,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/6/0",
          position: 0,
          productId: 6,
          colorId: 6,
        },
        {
          id: 35,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/6/1",
          position: 1,
          productId: 6,
          colorId: 6,
        },
        {
          id: 36,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-6/6/2",
          position: 2,
          productId: 6,
          colorId: 6,
        },
      ],
      variants: [
        {
          id: 48,
          code: "Á-6-TRẮNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 5,
          productId: 6,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 47,
          code: "Á-6-TRẮNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 4,
          productId: 6,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 46,
          code: "Á-6-TRẮNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 3,
          productId: 6,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 45,
          code: "Á-6-TRẮNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 2,
          productId: 6,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 44,
          code: "Á-6-ĐEN-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 5,
          productId: 6,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 43,
          code: "Á-6-ĐEN-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 4,
          productId: 6,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 42,
          code: "Á-6-ĐEN-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 3,
          productId: 6,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 41,
          code: "Á-6-ĐEN-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 1,
          sizeId: 2,
          productId: 6,
          color: {
            id: 1,
            name: "ĐEN",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 1,
          name: "ĐEN",
        },
        {
          id: 6,
          name: "TRẮNG",
        },
      ],
    },
    {
      id: 7,
      code: "Á-7",
      urlHandle: "ao-phong-nam-phoi-vai-sieu-mong-7",
      name: "Áo Phông Nam Phối Vải Siêu Mỏng",
      metaDesc:
        "Kiểu dáng Slim fit ôm sát tôn lên đường nét cơ thể, giúp bạn tự tin và khoẻ khoắn trong mọi hoạt động từ đi làm, đi chơi đến dự tiệc. Sản phẩm hoàn hảo cho phái mạnh hiện đại - tự tin khẳng định phong cách.",
      display: true,
      inventoryStatus: true,
      originalPrice: "290000",
      salePrice: null,
      createdDate: "2025-05-25T10:06:08.335Z",
      updatedDate: "2025-05-25T10:06:09.714Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 37,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/6/0",
          position: 0,
          productId: 7,
          colorId: 6,
        },
        {
          id: 38,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/6/1",
          position: 1,
          productId: 7,
          colorId: 6,
        },
        {
          id: 39,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/6/2",
          position: 2,
          productId: 7,
          colorId: 6,
        },
        {
          id: 40,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/4/0",
          position: 0,
          productId: 7,
          colorId: 4,
        },
        {
          id: 41,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/4/1",
          position: 1,
          productId: 7,
          colorId: 4,
        },
        {
          id: 42,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-7/4/2",
          position: 2,
          productId: 7,
          colorId: 4,
        },
      ],
      variants: [
        {
          id: 56,
          code: "Á-7-TRẮNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 5,
          productId: 7,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 55,
          code: "Á-7-TRẮNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 4,
          productId: 7,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 54,
          code: "Á-7-TRẮNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 3,
          productId: 7,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 53,
          code: "Á-7-TRẮNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 6,
          sizeId: 2,
          productId: 7,
          color: {
            id: 6,
            name: "TRẮNG",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 52,
          code: "Á-7-XANH LÁ-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 4,
          sizeId: 5,
          productId: 7,
          color: {
            id: 4,
            name: "XANH LÁ",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 51,
          code: "Á-7-XANH LÁ-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 4,
          sizeId: 4,
          productId: 7,
          color: {
            id: 4,
            name: "XANH LÁ",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 50,
          code: "Á-7-XANH LÁ-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 4,
          sizeId: 3,
          productId: 7,
          color: {
            id: 4,
            name: "XANH LÁ",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 49,
          code: "Á-7-XANH LÁ-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 4,
          sizeId: 2,
          productId: 7,
          color: {
            id: 4,
            name: "XANH LÁ",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 4,
          name: "XANH LÁ",
        },
        {
          id: 6,
          name: "TRẮNG",
        },
      ],
    },
    {
      id: 8,
      code: "S-8",
      urlHandle: "so-mi-coc-tay-nam-nano-ke-caro-tui-nguc-8",
      name: "Sơ Mi Cộc Tay Nam Nano Kẻ Caro Túi Ngực",
      metaDesc:
        "Chất liệu: Jeans cotton co giãn nhẹ\n\nThành phần:100% Polyester\n\nƯu điểm chất liệu:\n\nHạn chế nhăn nhàu: Phom áo luôn giữ dáng, không lo xô lệch nhờ sợi nano mảnh, giúp vải nhẹ và bền.\n\nMềm mại: Cảm giác êm ái và thoải mái khi mặc suốt cả ngày.\n\nThấm hút nhanh: Vải có khả năng hút ẩm hiệu quả, giữ cơ thể luôn khô ráo.\n\nChống UV tới 53+: Bảo vệ làn da khỏi tác hại của tia UV, giúp bảo vệ da dưới ánh nắng mặt trời.\n\nNhanh khô: Vải khô nhanh chóng, lý tưởng cho các hoạt động ngoài trời hoặc vận động.\n\nĐặc điểm thiết kế:\n\nThiết kế trẻ trung: Bề mặt vải được thiết kế sọc kẻ tạo nên sự trẻ trung khi mặc\n\nĐiểm nhấn tiện lợi: Túi ngực tiện lợi, dễ dàng sử dụng.",
      display: true,
      inventoryStatus: true,
      originalPrice: "450000",
      salePrice: null,
      createdDate: "2025-05-25T10:07:17.820Z",
      updatedDate: "2025-05-25T10:07:18.834Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 43,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/S-8/3/0",
          position: 0,
          productId: 8,
          colorId: 3,
        },
        {
          id: 44,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/S-8/3/1",
          position: 1,
          productId: 8,
          colorId: 3,
        },
        {
          id: 45,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/S-8/3/2",
          position: 2,
          productId: 8,
          colorId: 3,
        },
        {
          id: 46,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/S-8/3/3",
          position: 3,
          productId: 8,
          colorId: 3,
        },
      ],
      variants: [
        {
          id: 60,
          code: "S-8-XANH DƯƠNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 5,
          productId: 8,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 59,
          code: "S-8-XANH DƯƠNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 4,
          productId: 8,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 58,
          code: "S-8-XANH DƯƠNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 3,
          productId: 8,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 57,
          code: "S-8-XANH DƯƠNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 2,
          productId: 8,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 3,
          name: "XANH NAVY",
        },
      ],
    },
    {
      id: 9,
      code: "Á-9",
      urlHandle: "ao-yoguu-sweater-in-chu-9",
      name: "Áo Yoguu Sweater In Chữ",
      metaDesc:
        "Chất liệu: Jeans cotton co giãn nhẹ\n\nThành phần:100% Polyester\n\nƯu điểm chất liệu:\n\nHạn chế nhăn nhàu: Phom áo luôn giữ dáng, không lo xô lệch nhờ sợi nano mảnh, giúp vải nhẹ và bền.\n\nMềm mại: Cảm giác êm ái và thoải mái khi mặc suốt cả ngày.\n\nThấm hút nhanh: Vải có khả năng hút ẩm hiệu quả, giữ cơ thể luôn khô ráo.\n\nChống UV tới 53+: Bảo vệ làn da khỏi tác hại của tia UV, giúp bảo vệ da dưới ánh nắng mặt trời.\n\nNhanh khô: Vải khô nhanh chóng, lý tưởng cho các hoạt động ngoài trời hoặc vận động.\n\nĐặc điểm thiết kế:\n\nThiết kế trẻ trung: Bề mặt vải được thiết kế sọc kẻ tạo nên sự trẻ trung khi mặc\n\nĐiểm nhấn tiện lợi: Túi ngực tiện lợi, dễ dàng sử dụng.",
      display: true,
      inventoryStatus: true,
      originalPrice: "450000",
      salePrice: null,
      createdDate: "2025-05-25T10:08:31.298Z",
      updatedDate: "2025-05-25T10:08:32.683Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 47,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/7/0",
          position: 0,
          productId: 9,
          colorId: 7,
        },
        {
          id: 48,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/7/1",
          position: 1,
          productId: 9,
          colorId: 7,
        },
        {
          id: 49,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/7/2",
          position: 2,
          productId: 9,
          colorId: 7,
        },
        {
          id: 50,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/8/0",
          position: 0,
          productId: 9,
          colorId: 8,
        },
        {
          id: 51,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/8/1",
          position: 1,
          productId: 9,
          colorId: 8,
        },
        {
          id: 52,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-9/8/2",
          position: 2,
          productId: 9,
          colorId: 8,
        },
      ],
      variants: [
        {
          id: 68,
          code: "Á-9-BE-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 5,
          productId: 9,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 67,
          code: "Á-9-BE-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 4,
          productId: 9,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 66,
          code: "Á-9-BE-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 3,
          productId: 9,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 65,
          code: "Á-9-BE-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 8,
          sizeId: 2,
          productId: 9,
          color: {
            id: 8,
            name: "BE",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 64,
          code: "Á-9-NÂU-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 5,
          productId: 9,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 63,
          code: "Á-9-NÂU-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 4,
          productId: 9,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 62,
          code: "Á-9-NÂU-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 3,
          productId: 9,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 61,
          code: "Á-9-NÂU-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 7,
          sizeId: 2,
          productId: 9,
          color: {
            id: 7,
            name: "NÂU",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 7,
          name: "NÂU",
        },
        {
          id: 8,
          name: "BE",
        },
      ],
    },
    {
      id: 10,
      code: "Á-10",
      urlHandle: "ao-ni-nam-relax-co-co-co-ban-10",
      name: "Áo Nỉ Nam Relax Có Cổ Cơ Bản",
      metaDesc:
        "Kiểu dáng Slim fit ôm sát tôn lên đường nét cơ thể, giúp bạn tự tin và khoẻ khoắn trong mọi hoạt động từ đi làm, đi chơi đến dự tiệc. Sản phẩm hoàn hảo cho phái mạnh hiện đại - tự tin khẳng định phong cách.",
      display: true,
      inventoryStatus: true,
      originalPrice: "450000",
      salePrice: null,
      createdDate: "2025-05-25T10:09:47.046Z",
      updatedDate: "2025-05-25T10:09:48.447Z",
      promotionId: null,
      categoryId: 5,
      brandId: 1,
      viewCount: 0,
      saleCount: 0,
      category: {
        id: 5,
        name: "Áo nam",
        urlHandle: "Ao-nam",
      },
      brand: {
        id: 1,
        name: "yody",
      },
      photos: [
        {
          id: 53,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/2/0",
          position: 0,
          productId: 10,
          colorId: 2,
        },
        {
          id: 54,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/2/1",
          position: 1,
          productId: 10,
          colorId: 2,
        },
        {
          id: 55,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/2/2",
          position: 2,
          productId: 10,
          colorId: 2,
        },
        {
          id: 56,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/3/0",
          position: 0,
          productId: 10,
          colorId: 3,
        },
        {
          id: 57,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/3/1",
          position: 1,
          productId: 10,
          colorId: 3,
        },
        {
          id: 58,
          url: "https://fstore-nbphuoc.s3.ap-southeast-1.amazonaws.com/products/Á-10/3/2",
          position: 2,
          productId: 10,
          colorId: 3,
        },
      ],
      variants: [
        {
          id: 76,
          code: "Á-10-XANH DƯƠNG-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 5,
          productId: 10,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 75,
          code: "Á-10-XANH DƯƠNG-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 4,
          productId: 10,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 74,
          code: "Á-10-XANH DƯƠNG-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 3,
          productId: 10,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 73,
          code: "Á-10-XANH DƯƠNG-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 3,
          sizeId: 2,
          productId: 10,
          color: {
            id: 3,
            name: "XANH NAVY",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
        {
          id: 72,
          code: "Á-10-XÁM-2XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 5,
          productId: 10,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 5,
            name: "2XL",
          },
        },
        {
          id: 71,
          code: "Á-10-XÁM-XL",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 4,
          productId: 10,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 4,
            name: "XL",
          },
        },
        {
          id: 70,
          code: "Á-10-XÁM-L",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 3,
          productId: 10,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 3,
            name: "L",
          },
        },
        {
          id: 69,
          code: "Á-10-XÁM-M",
          inventoryQuantity: 100,
          instock: true,
          colorId: 2,
          sizeId: 2,
          productId: 10,
          color: {
            id: 2,
            name: "XÁM",
          },
          size: {
            id: 2,
            name: "M",
          },
        },
      ],
      colors: [
        {
          id: 2,
          name: "XÁM",
        },
        {
          id: 3,
          name: "XANH NAVY",
        },
      ],
    },
  ],
  page: 0,
  limit: 10,
  total: 50,
  totalPages: 5,
};
